# Generated by Django 5.0.6 on 2024-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.CharField(choices=[({'name': 'Pyhsics'}, [('name', 'Pyhsics')])], default='General', max_length=100),
        ),
    ]
