# Generated by Django 5.0.6 on 2024-05-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.CharField(choices=[({'name': 'Pyhsics'}, [('name', 'Pyhsics')]), ({'name': 'Cryptocurrency'}, [('name', 'Cryptocurrency')])], default='General', max_length=100),
        ),
    ]
