# Generated by Django 5.0.6 on 2024-05-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_learninghistory_queried_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninghistory',
            name='card',
            field=models.IntegerField(),
        ),
    ]
